from pathlib import Path
import heapq
import os
import shutil

import numpy as np

from config import (
    DATASET_DIR,
    VOCAB_FILE,
    MERGES_FILE,
    MERGE_STATE_FILE,
    HEAP_FILE,
    OFFSET_DTYPE,
    MAX_VOCAB_SIZE,
    NUM_MERGES,
    MIN_PAIR_FREQ,
    MIN_PAIR_FREQ_LOAD,
    CHECKPOINT_INTERVAL,
    PAIR_BASE,
    DO_NOT_MERGE,
)

from utils import (
    load_json,
    save_json,
    save_numpy,
)


# ============================================================
# FILES
# ============================================================

TOKENS_FILE = DATASET_DIR / "tokens.npy"
NEXT_FILE = DATASET_DIR / "next.npy"
PREV_FILE = DATASET_DIR / "prev.npy"
ACTIVE_FILE = DATASET_DIR / "active.npy"
OFFSETS_FILE = DATASET_DIR / "offsets.npy"

PAIR_IDS_FILE = DATASET_DIR / "pair_ids.npy"
PAIR_COUNTS_FILE = DATASET_DIR / "pair_counts.npy"
PAIR_HEADS_FILE = DATASET_DIR / "pair_heads.npy"
PAIR_TAILS_FILE = DATASET_DIR / "pair_tails.npy"

OCC_NEXT_FILE = DATASET_DIR / "occ_next.npy"
OCC_PREV_FILE = DATASET_DIR / "occ_prev.npy"


# ============================================================
# CHECKPOINT DIRECTORIES
# ============================================================

CHECKPOINT_DIR = DATASET_DIR / "checkpoints"

LATEST_CHECKPOINT_DIR = (
    CHECKPOINT_DIR / "latest"
)

TEMP_CHECKPOINT_DIR = (
    DATASET_DIR / "checkpoint_tmp"
)

OLD_CHECKPOINT_DIR = (
    DATASET_DIR / "checkpoint_old"
)

# ============================================================
# PAIR ENCODING
# ============================================================

def encode_pair(left, right):
    """
    Convert two token IDs into one unique integer pair ID.
    """

    return (
        int(left) * int(PAIR_BASE)
        + int(right)
    )


def decode_pair(pair_id):
    """
    Convert pair ID back into:

        left_token_id, right_token_id
    """

    pair_id = int(pair_id)

    return (
        pair_id // int(PAIR_BASE),
        pair_id % int(PAIR_BASE),
    )


# ============================================================
# CHECKPOINT FILE MAP
# ============================================================

def checkpoint_files(directory):
    """
    Return all files belonging to one checkpoint.
    """

    return {
        "tokens": directory / "tokens.npy",
        "next": directory / "next.npy",
        "prev": directory / "prev.npy",
        "active": directory / "active.npy",
        "offsets": directory / "offsets.npy",

        "pair_ids": directory / "pair_ids.npy",
        "pair_counts": directory / "pair_counts.npy",
        "pair_heads": directory / "pair_heads.npy",
        "pair_tails": directory / "pair_tails.npy",

        "occ_next": directory / "occ_next.npy",
        "occ_prev": directory / "occ_prev.npy",

        "heap": directory / "heap.npy",

        "merges": directory / "merges.json",
        "vocab": directory / "vocab.json",
    }


# ============================================================
# LOAD MERGE STATE
# ============================================================

def load_merge_state():
    """
    Return:

        completed_merges
        checkpoint_directory

    If no checkpoint has been created yet, return:

        0, None

    In that case, the initial files generated by corpus.py
    are loaded directly from DATASET_DIR.
    """

    if not MERGE_STATE_FILE.exists():

        return 0, None

    state = load_json(
        MERGE_STATE_FILE
    )

    completed_merges = int(
        state.get(
            "completed_merges",
            0,
        )
    )

    checkpoint_name = state.get(
        "checkpoint",
        None,
    )

    if checkpoint_name is None:

        return completed_merges, None

    checkpoint_path = (
        DATASET_DIR
        / checkpoint_name
    )

    return completed_merges, checkpoint_path


# ============================================================
# LOAD COMPLETE STATE
# ============================================================

def load_state():

    (
        completed_merges,
        checkpoint_path,
    ) = load_merge_state()

    # --------------------------------------------------------
    # FIRST RUN
    # --------------------------------------------------------

    if checkpoint_path is None:

        directory = DATASET_DIR

        print(
            "\nLoading initial state from corpus.py..."
        )

    # --------------------------------------------------------
    # RESUME
    # --------------------------------------------------------

    else:

        directory = checkpoint_path

        print(
            "\nResuming BPE..."
        )

        print(
            f"Checkpoint : {directory}"
        )

        print(
            f"Completed  : "
            f"{completed_merges:,} merges"
        )

    files = checkpoint_files(
        directory
    )

    # --------------------------------------------------------
    # NODE STRUCTURES
    # --------------------------------------------------------

    tokens = np.load(
        files["tokens"],
        allow_pickle=False,
    )

    next_node = np.load(
        files["next"],
        allow_pickle=False,
    )

    prev_node = np.load(
        files["prev"],
        allow_pickle=False,
    )

    active = np.load(
        files["active"],
        allow_pickle=False,
    )

    offsets = np.load(
        files["offsets"],
        allow_pickle=False,
    )

    # --------------------------------------------------------
    # PAIR STRUCTURES
    # --------------------------------------------------------

    pair_ids = np.load(
        files["pair_ids"],
        allow_pickle=False,
    )

    pair_counts = np.load(
        files["pair_counts"],
        allow_pickle=False,
    )

    pair_heads = np.load(
        files["pair_heads"],
        allow_pickle=False,
    )

    pair_tails = np.load(
        files["pair_tails"],
        allow_pickle=False,
    )

    occ_next = np.load(
        files["occ_next"],
        allow_pickle=False,
    )

    occ_prev = np.load(
        files["occ_prev"],
        allow_pickle=False,
    )

    # --------------------------------------------------------
    # HEAP
    # --------------------------------------------------------

    heap_array = np.load(
        files["heap"],
        allow_pickle=False,
    )

    # --------------------------------------------------------
    # MERGE HISTORY
    # --------------------------------------------------------

    if files["merges"].exists():

        merges = load_json(
            files["merges"]
        )

    else:

        merges = []

        # --------------------------------------------------------
    # VOCABULARY
    # --------------------------------------------------------

    if files["vocab"].exists():

        vocab = load_json(
            files["vocab"]
        )

    else:

        vocab = None

    return (
        completed_merges,
        tokens,
        next_node,
        prev_node,
        active,
        offsets,
        pair_ids,
        pair_counts,
        pair_heads,
        pair_tails,
        occ_next,
        occ_prev,
        heap_array,
        merges,
        vocab,
    )


# ============================================================
# VALIDATE STATE
# ============================================================

def validate_state(
    tokens,
    next_node,
    prev_node,
    active,
    offsets,
    pair_ids,
    pair_counts,
    pair_heads,
    pair_tails,
    occ_next,
    occ_prev,
):

    node_count = len(tokens)

    for array in (
        next_node,
        prev_node,
        active,
        occ_next,
        occ_prev,
    ):

        if len(array) != node_count:

            raise RuntimeError(
                "Node arrays have inconsistent lengths."
            )

    pair_count = len(
        pair_ids
    )

    if len(pair_counts) != pair_count:
        raise RuntimeError(
            "pair_counts length mismatch."
        )

    if len(pair_heads) != pair_count:
        raise RuntimeError(
            "pair_heads length mismatch."
        )

    if len(pair_tails) != pair_count:
        raise RuntimeError(
            "pair_tails length mismatch."
        )

    if len(offsets) == 0:

        raise RuntimeError(
            "offsets.npy is empty."
        )


# ============================================================
# BUILD PAIR LOOKUP
# ============================================================

def build_pair_lookup(pair_ids):
    """
    pair_id -> slot

    Python dictionary gives O(1) average lookup.
    """

    return {
        int(pair_id): slot
        for slot, pair_id
        in enumerate(pair_ids)
    }


# ============================================================
# LOAD HEAP
# ============================================================

def load_heap(heap_array):
    """
    corpus.py saves heap entries as:

        [-frequency, pair_id]

    Convert them into a Python heapq heap.
    """

    heap = [
        (
            int(row[0]),
            int(row[1]),
        )
        for row in heap_array
    ]

    heapq.heapify(
        heap
    )

    return heap


# ============================================================
# PUSH UPDATED PAIR INTO HEAP
# ============================================================

def push_heap_entry(
    heap,
    pair_id,
    pair_to_slot,
    pair_counts,
):

    slot = pair_to_slot.get(
        int(pair_id)
    )

    if slot is None:

        return

    count = int(
        pair_counts[slot]
    )

    if count >= MIN_PAIR_FREQ_LOAD:

        heapq.heappush(
            heap,
            (
                -count,
                int(pair_id),
            ),
        )


# ============================================================
# GET HIGHEST-FREQUENCY PAIR
# ============================================================

def get_best_pair(
    heap,
    pair_to_slot,
    pair_counts,
):

    while heap:

        negative_count, pair_id = heap[0]

        slot = pair_to_slot.get(
            int(pair_id)
        )

        # Pair no longer exists.
        if slot is None:

            heapq.heappop(
                heap
            )

            continue

        current_count = int(
            pair_counts[slot]
        )

        stored_count = -int(
            negative_count
        )

        # ----------------------------------------------------
        # LAZY HEAP UPDATE
        # ----------------------------------------------------

        if stored_count != current_count:

            heapq.heappop(
                heap
            )

            continue

        if current_count < MIN_PAIR_FREQ:
            if current_count < MIN_PAIR_FREQ_LOAD:
                heapq.heappop(heap)
                continue

            return None, 0

        return (
            int(pair_id),
            current_count,
        )

    return None, 0


# ============================================================
# REMOVE OCCURRENCE
# ============================================================

def remove_occurrence(
    pair_id,
    node,
    pair_to_slot,
    pair_counts,
    pair_heads,
    pair_tails,
    occ_next,
    occ_prev,
    changed_pairs,
):

    pair_id = int(
        pair_id
    )

    node = int(
        node
    )

    slot = pair_to_slot.get(
        pair_id
    )

    if slot is None:

        return

    previous_occ = int(
        occ_prev[node]
    )

    next_occurrence = int(
        occ_next[node]
    )

    # --------------------------------------------------------
    # UPDATE PREVIOUS OCCURRENCE
    # --------------------------------------------------------

    if previous_occ != -1:

        occ_next[
            previous_occ
        ] = next_occurrence

    else:

        pair_heads[
            slot
        ] = next_occurrence

    # --------------------------------------------------------
    # UPDATE NEXT OCCURRENCE
    # --------------------------------------------------------

    if next_occurrence != -1:

        occ_prev[
            next_occurrence
        ] = previous_occ

    else:

        pair_tails[
            slot
        ] = previous_occ

    occ_prev[node] = -1
    occ_next[node] = -1

    pair_counts[
        slot
    ] -= 1

    changed_pairs.add(
        pair_id
    )


# ============================================================
# ADD OCCURRENCE
# ============================================================

def add_occurrence(
    pair_id,
    node,
    pair_to_slot,
    pair_ids,
    pair_counts,
    pair_heads,
    pair_tails,
    occ_next,
    occ_prev,
    changed_pairs,
):

    pair_id = int(
        pair_id
    )

    node = int(
        node
    )

    slot = pair_to_slot.get(
        pair_id
    )

    # --------------------------------------------------------
    # NEW PAIR TYPE
    # --------------------------------------------------------

    if slot is None:

        slot = len(
            pair_ids
        )

        pair_to_slot[
            pair_id
        ] = slot

        pair_ids.append(
            pair_id
        )

        pair_counts.append(
            0
        )

        pair_heads.append(
            -1
        )

        pair_tails.append(
            -1
        )

    # --------------------------------------------------------
    # APPEND TO OCCURRENCE LIST
    # --------------------------------------------------------

    tail = int(
        pair_tails[slot]
    )

    if tail == -1:

        pair_heads[
            slot
        ] = node

        pair_tails[
            slot
        ] = node

        occ_prev[node] = -1
        occ_next[node] = -1

    else:

        occ_next[
            tail
        ] = node

        occ_prev[
            node
        ] = tail

        occ_next[node] = -1

        pair_tails[
            slot
        ] = node

    pair_counts[
        slot
    ] += 1

    changed_pairs.add(
        pair_id
    )


# ============================================================
# MERGE ONE OCCURRENCE
# ============================================================

def merge_one_occurrence(
    left_node,
    merge_pair_id,
    new_token_id,
    pair_to_slot,
    pair_ids,
    pair_counts,
    pair_heads,
    pair_tails,
    tokens,
    next_node,
    prev_node,
    active,
    occ_next,
    occ_prev,
    changed_pairs,
):

    left_node = int(
        left_node
    )

    # --------------------------------------------------------
    # VALIDATE LEFT NODE
    # --------------------------------------------------------

    if not active[left_node]:

        return False

    right_node = int(
        next_node[left_node]
    )

    if right_node == -1:

        return False

    if not active[right_node]:

        return False

    # --------------------------------------------------------
    # VALIDATE PAIR
    # --------------------------------------------------------
    #
    # Important for overlapping pairs.
    #
    # Example:
    #
    #     A A A
    #
    # When the first A+A is merged, the second occurrence
    # can become stale. We therefore verify it before merging.

    actual_pair = encode_pair(
        tokens[left_node],
        tokens[right_node],
    )

    if actual_pair != int(
        merge_pair_id
    ):

        return False

    # --------------------------------------------------------
    # SAVE NEIGHBORS
    # --------------------------------------------------------

    left_neighbor = int(
        prev_node[left_node]
    )

    right_neighbor = int(
        next_node[right_node]
    )

    # --------------------------------------------------------
    # REMOVE (LEFT_NEIGHBOR, LEFT)
    # --------------------------------------------------------

    if left_neighbor != -1:

        old_pair = encode_pair(
            tokens[left_neighbor],
            tokens[left_node],
        )

        remove_occurrence(
            old_pair,
            left_neighbor,
            pair_to_slot,
            pair_counts,
            pair_heads,
            pair_tails,
            occ_next,
            occ_prev,
            changed_pairs,
        )

    # --------------------------------------------------------
    # REMOVE (LEFT, RIGHT)
    # --------------------------------------------------------

    remove_occurrence(
        merge_pair_id,
        left_node,
        pair_to_slot,
        pair_counts,
        pair_heads,
        pair_tails,
        occ_next,
        occ_prev,
        changed_pairs,
    )

    # --------------------------------------------------------
    # REMOVE (RIGHT, RIGHT_NEIGHBOR)
    # --------------------------------------------------------

    if right_neighbor != -1:

        old_pair = encode_pair(
            tokens[right_node],
            tokens[right_neighbor],
        )

        remove_occurrence(
            old_pair,
            right_node,
            pair_to_slot,
            pair_counts,
            pair_heads,
            pair_tails,
            occ_next,
            occ_prev,
            changed_pairs,
        )

    # --------------------------------------------------------
    # MERGE
    # --------------------------------------------------------

    tokens[
        left_node
    ] = new_token_id

    # Remove right node from linked list.

    next_node[
        left_node
    ] = right_neighbor

    if right_neighbor != -1:

        prev_node[
            right_neighbor
        ] = left_node

    active[
        right_node
    ] = False

    next_node[
        right_node
    ] = -1

    prev_node[
        right_node
    ] = -1

    # --------------------------------------------------------
    # ADD (LEFT_NEIGHBOR, NEW_TOKEN)
    # --------------------------------------------------------

    if left_neighbor != -1:

        new_pair = encode_pair(
            tokens[left_neighbor],
            new_token_id,
        )

        add_occurrence(
            new_pair,
            left_neighbor,
            pair_to_slot,
            pair_ids,
            pair_counts,
            pair_heads,
            pair_tails,
            occ_next,
            occ_prev,
            changed_pairs,
        )

    # --------------------------------------------------------
    # ADD (NEW_TOKEN, RIGHT_NEIGHBOR)
    # --------------------------------------------------------

    if right_neighbor != -1:

        new_pair = encode_pair(
            new_token_id,
            tokens[right_neighbor],
        )

        add_occurrence(
            new_pair,
            left_node,
            pair_to_slot,
            pair_ids,
            pair_counts,
            pair_heads,
            pair_tails,
            occ_next,
            occ_prev,
            changed_pairs,
        )

    return True


# ============================================================
# MERGE ALL OCCURRENCES
# ============================================================

def merge_pair(
    merge_pair_id,
    new_token_id,
    pair_to_slot,
    pair_ids,
    pair_counts,
    pair_heads,
    pair_tails,
    tokens,
    next_node,
    prev_node,
    active,
    occ_next,
    occ_prev,
    heap,
):

    slot = pair_to_slot.get(
        int(merge_pair_id)
    )

    if slot is None:

        return 0

    current_node = int(
        pair_heads[slot]
    )

    merged_count = 0

    # Every pair whose count changes during this merge goes
    # into this set.
    #
    # Therefore we NEVER scan all pair types just to update
    # the heap.

    changed_pairs = set()

    while current_node != -1:

        # Save before modifying occurrence links.
        next_occurrence = int(
            occ_next[current_node]
        )

        success = merge_one_occurrence(
            current_node,
            merge_pair_id,
            new_token_id,
            pair_to_slot,
            pair_ids,
            pair_counts,
            pair_heads,
            pair_tails,
            tokens,
            next_node,
            prev_node,
            active,
            occ_next,
            occ_prev,
            changed_pairs,
        )

        if success:

            merged_count += 1

        current_node = next_occurrence

    # --------------------------------------------------------
    # SELECTED PAIR IS NOW EMPTY
    # --------------------------------------------------------

    slot = pair_to_slot.get(
        int(merge_pair_id)
    )

    if slot is not None:

        pair_counts[
            slot
        ] = 0

        pair_heads[
            slot
        ] = -1

        pair_tails[
            slot
        ] = -1

    # --------------------------------------------------------
    # UPDATE HEAP
    # --------------------------------------------------------
    #
    # Only changed pair types are touched.
    #
    # Old heap entries remain there and are removed lazily
    # by get_best_pair().

    for pair_id in changed_pairs:

        push_heap_entry(
            heap,
            pair_id,
            pair_to_slot,
            pair_counts,
        )

    return merged_count


# ============================================================
# SAVE CHECKPOINT
# ============================================================

def save_checkpoint(
    completed_merges,
    tokens,
    next_node,
    prev_node,
    active,
    offsets,
    pair_ids,
    pair_counts,
    pair_heads,
    pair_tails,
    occ_next,
    occ_prev,
    heap,
    merges,
    vocab,
):
    """
    Safely save the latest BPE checkpoint.

    Only one completed checkpoint is kept:

        checkpoints/latest/

    A temporary checkpoint is completely written and verified
    before replacing the previous checkpoint.

    If the program is interrupted during saving, the previous
    checkpoint remains recoverable.
    """

    print(
        f"\nSaving checkpoint after "
        f"{completed_merges:,} merges..."
    )

    CHECKPOINT_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    # --------------------------------------------------------
    # CLEAN OLD TEMPORARY DIRECTORIES
    # --------------------------------------------------------

    if TEMP_CHECKPOINT_DIR.exists():

        shutil.rmtree(
            TEMP_CHECKPOINT_DIR
        )

    if OLD_CHECKPOINT_DIR.exists():

        shutil.rmtree(
            OLD_CHECKPOINT_DIR
        )

    TEMP_CHECKPOINT_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    files = checkpoint_files(
        TEMP_CHECKPOINT_DIR
    )

    # --------------------------------------------------------
    # CONVERT DYNAMIC PAIR STRUCTURES
    # --------------------------------------------------------

    pair_ids_array = np.asarray(
        pair_ids,
        dtype=np.int64,
    )

    pair_counts_array = np.asarray(
        pair_counts,
        dtype=np.int64,
    )

    pair_heads_array = np.asarray(
        pair_heads,
        dtype=OFFSET_DTYPE,
    )

    pair_tails_array = np.asarray(
        pair_tails,
        dtype=OFFSET_DTYPE,
    )

    # --------------------------------------------------------
    # SAVE NUMPY FILES
    # --------------------------------------------------------

    save_numpy(
        tokens,
        files["tokens"],
    )

    save_numpy(
        next_node,
        files["next"],
    )

    save_numpy(
        prev_node,
        files["prev"],
    )

    save_numpy(
        active,
        files["active"],
    )

    save_numpy(
        offsets,
        files["offsets"],
    )

    save_numpy(
        pair_ids_array,
        files["pair_ids"],
    )

    save_numpy(
        pair_counts_array,
        files["pair_counts"],
    )

    save_numpy(
        pair_heads_array,
        files["pair_heads"],
    )

    save_numpy(
        pair_tails_array,
        files["pair_tails"],
    )

    save_numpy(
        occ_next,
        files["occ_next"],
    )

    save_numpy(
        occ_prev,
        files["occ_prev"],
    )

    # --------------------------------------------------------
    # SAVE HEAP
    # --------------------------------------------------------

    heap_array = np.asarray(
        heap,
        dtype=np.int64,
    )

    save_numpy(
        heap_array,
        files["heap"],
    )

    # --------------------------------------------------------
    # SAVE MERGE HISTORY
    # --------------------------------------------------------

    save_json(
        merges,
        files["merges"],
    )

    # --------------------------------------------------------
    # SAVE VOCABULARY
    # --------------------------------------------------------

    save_json(
        vocab,
        files["vocab"],
    )

    # --------------------------------------------------------
    # VERIFY TEMPORARY CHECKPOINT
    # --------------------------------------------------------

    for path in files.values():

        if not path.exists():

            raise RuntimeError(
                "Checkpoint file missing:\n"
                f"{path}"
            )

    # --------------------------------------------------------
    # SAFELY REPLACE PREVIOUS CHECKPOINT
    # --------------------------------------------------------

    if LATEST_CHECKPOINT_DIR.exists():

        # Move old valid checkpoint out of the way.
        os.replace(
            LATEST_CHECKPOINT_DIR,
            OLD_CHECKPOINT_DIR,
        )

    # Move the completely written checkpoint into place.
    os.replace(
        TEMP_CHECKPOINT_DIR,
        LATEST_CHECKPOINT_DIR,
    )

    # --------------------------------------------------------
    # UPDATE MERGE STATE LAST
    # --------------------------------------------------------

    save_json(
        {
            "completed_merges": completed_merges,
            "checkpoint": "checkpoints/latest",
        },
        MERGE_STATE_FILE,
    )

    # --------------------------------------------------------
    # OLD CHECKPOINT NO LONGER NEEDED
    # --------------------------------------------------------

    if OLD_CHECKPOINT_DIR.exists():

        shutil.rmtree(
            OLD_CHECKPOINT_DIR
        )

    print(
        "Checkpoint saved."
    )

# ============================================================
# MAIN BPE LOOP
# ============================================================

def run_bpe():

    print("=" * 60)
    print("BPE MERGE ENGINE")
    print("=" * 60)

    # --------------------------------------------------------
    # LOAD STATE
    # --------------------------------------------------------

    (
        completed_merges,
        tokens,
        next_node,
        prev_node,
        active,
        offsets,
        pair_ids,
        pair_counts,
        pair_heads,
        pair_tails,
        occ_next,
        occ_prev,
        heap_array,
        merges,
        checkpoint_vocab,
    ) = load_state()

    # --------------------------------------------------------
    # LOAD CORRECT VOCABULARY
    # --------------------------------------------------------

    if checkpoint_vocab is not None:

        vocab = checkpoint_vocab

    else:

        vocab = load_json(
            VOCAB_FILE
        )

    reverse_vocab = {
        int(token_id): token
        for token, token_id
        in vocab.items()
    }

    print(
        f"Vocabulary size: "
        f"{len(vocab):,}"
    )

    validate_state(
        tokens,
        next_node,
        prev_node,
        active,
        offsets,
        pair_ids,
        pair_counts,
        pair_heads,
        pair_tails,
        occ_next,
        occ_prev,
    )

    # --------------------------------------------------------
    # PAIR LISTS
    # --------------------------------------------------------

    pair_ids = [
        int(x)
        for x in pair_ids
    ]

    pair_counts = [
        int(x)
        for x in pair_counts
    ]

    pair_heads = [
        int(x)
        for x in pair_heads
    ]

    pair_tails = [
        int(x)
        for x in pair_tails
    ]

    # --------------------------------------------------------
    # PAIR LOOKUP
    # --------------------------------------------------------

    print(
        "\nBuilding pair lookup..."
    )

    pair_to_slot = build_pair_lookup(
        pair_ids
    )

    print(
        f"Unique pair types: "
        f"{len(pair_ids):,}"
    )

    # --------------------------------------------------------
    # HEAP
    # --------------------------------------------------------

    print(
        "\nLoading heap..."
    )

    heap = load_heap(
        heap_array
    )

    print(
        f"Heap entries: "
        f"{len(heap):,}"
    )

    # --------------------------------------------------------
    # CHECK MERGE HISTORY
    # --------------------------------------------------------

    if len(merges) != completed_merges:

        raise RuntimeError(
            "merge_state.json and merges.json "
            "disagree about completed merges."
        )

    # --------------------------------------------------------
    # MAIN LOOP
    # --------------------------------------------------------

    while completed_merges < NUM_MERGES:

        pair_id, frequency = get_best_pair(
            heap,
            pair_to_slot,
            pair_counts,
        )

        if pair_id is None:

            print(
                "\nNo pair satisfies MIN_PAIR_FREQ."
            )

            break

        left_id, right_id = decode_pair(
            pair_id
        )

        # ----------------------------------------------------
        # TOKEN STRINGS
        # ----------------------------------------------------

        left_token = reverse_vocab.get(
            left_id
        )

        right_token = reverse_vocab.get(
            right_id
        )

        if left_token is None:

            raise RuntimeError(
                f"Token ID {left_id} "
                f"is missing from vocabulary."
            )

        if right_token is None:

            raise RuntimeError(
                f"Token ID {right_id} "
                f"is missing from vocabulary."
            )

        # ----------------------------------------------------
        # SPECIAL TOKEN SAFETY
        # ----------------------------------------------------

        if (
            left_token in DO_NOT_MERGE
            or right_token in DO_NOT_MERGE
        ):

            # This should never happen because corpus.py filters
            # these pairs, but it protects against a corrupt state.

            heapq.heappop(
                heap
            )

            continue

        # ----------------------------------------------------
        # NEW TOKEN
        # ----------------------------------------------------

        new_token = (
            left_token
            + right_token
        )

        if new_token in vocab:

            new_token_id = int(
                vocab[new_token]
            )

        else:

            new_token_id = len(
                vocab
            )

            if new_token_id >= MAX_VOCAB_SIZE:

                print(
                    "\nMaximum vocabulary size reached."
                )

                break

            vocab[
                new_token
            ] = new_token_id

            reverse_vocab[
                new_token_id
            ] = new_token

        # ----------------------------------------------------
        # DISPLAY
        # ----------------------------------------------------

        print(
            f"\nMerge "
            f"{completed_merges + 1:,}/"
            f"{NUM_MERGES:,}"
        )

        print(
            f"  Frequency : {frequency:,}"
        )

        print(
            f"  Pair      : "
            f"{left_token!r} + {right_token!r}"
        )

        print(
            f"  New token : {new_token!r}"
        )

        # ----------------------------------------------------
        # PERFORM MERGE
        # ----------------------------------------------------

        merged_count = merge_pair(
            pair_id,
            new_token_id,
            pair_to_slot,
            pair_ids,
            pair_counts,
            pair_heads,
            pair_tails,
            tokens,
            next_node,
            prev_node,
            active,
            occ_next,
            occ_prev,
            heap,
        )

        # ----------------------------------------------------
        # STALE PAIR
        # ----------------------------------------------------

        if merged_count == 0:

            heapq.heappop(
                heap
            )

            continue

        completed_merges += 1

        # ----------------------------------------------------
        # SAVE MERGE RULE
        # ----------------------------------------------------

        merges.append(
            [
                left_id,
                right_id,
                new_token_id,
            ]
        )

        print(
            f"  Occurrences: "
            f"{merged_count:,}"
        )

        # ----------------------------------------------------
        # CHECKPOINT
        # ----------------------------------------------------

        if (
            completed_merges
            % CHECKPOINT_INTERVAL
            == 0
        ):

            save_checkpoint(
                completed_merges,
                tokens,
                next_node,
                prev_node,
                active,
                offsets,
                pair_ids,
                pair_counts,
                pair_heads,
                pair_tails,
                occ_next,
                occ_prev,
                heap,
                merges,
                vocab,
            )

    # --------------------------------------------------------
    # FINAL SAVE
    # --------------------------------------------------------

    print(
        "\nSaving final state..."
    )

    save_checkpoint(
        completed_merges,
        tokens,
        next_node,
        prev_node,
        active,
        offsets,
        pair_ids,
        pair_counts,
        pair_heads,
        pair_tails,
        occ_next,
        occ_prev,
        heap,
        merges,
        vocab,
    )

    # --------------------------------------------------------
    # SUMMARY
    # --------------------------------------------------------

    print()
    print("=" * 60)
    print("BPE MERGING COMPLETE")
    print("=" * 60)

    print(
        f"Completed merges : "
        f"{completed_merges:,}"
    )

    print(
        f"Vocabulary size  : "
        f"{len(vocab):,}"
    )

    print(
        f"Merge rules      : "
        f"{len(merges):,}"
    )


# ============================================================
# ENTRY POINT
# ============================================================

if __name__ == "__main__":
    run_bpe()